[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "biwipy"
version = "0.11.0"
description = "Biwipy: cycling performance simulation with GRIB wind data"
authors = [
  { name="jacme", email="your.email@example.com" },
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "folium",
    "herbie-data",
    "rasterio",
    "pygrib",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff",
]
viz = [
    "plotly",
]
docs = [
    "sphinx>=7.0",
    "pydata-sphinx-theme",
    "myst-parser",
    "linkify-it-py",
    "nbsphinx",
    "sphinx-copybutton",
    "sphinx-autodoc-typehints",
    "sphinx-sitemap",
    "ipython",
    "jupyter",
]

[project.urls]
"Homepage" = "https://github.com/jacme31/biwipy"
"Bug Tracker" = "https://github.com/jacme31/biwipy/issues"
"Documentation" = "https://biwipy.readthedocs.io"

[tool.setuptools.packages.find]
where = ["."]
include = ["biwipy*"]
